### ISSUE TITLE
AnalysisData printDistributionChanges()

### ISSUE THREAD

**Issue by Blemm13** [IIS-ZPI/ZPI2020_IO1_Chrum#41]
1. Try to remove "if" by placing print before and after for loop for efficiency.

print (index 0)

for (1 to index last -1)

print (index last)

2. While passing values USD PLN week in the third case in main I get an exception caused by incorrect input because PLN isn't listed in nbp API:

Exception in thread "main" java.lang.NullPointerException: Cannot read the array length because "AnalysisData.distributionChangesRanges" is null
	at AnalysisData.printDistributionChanges(AnalysisData.java:240)
	at Main.main(Main.java:84)

**Comment by Blemm13** [comment]
Make there is a message in Main class after getting null response
